"""Add watch_providers column to Content

Revision ID: 4451bdc893fb
Revises: f7fe92c3508b
Create Date: 2026-08-17 00:42:51.829213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4451bdc893fb'
down_revision: Union[str, None] = 'f7fe92c3508b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('watch_providers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'watch_providers')
    # ### end Alembic commands ###
