"""Add performance indexes on content columns

Revision ID: b60ded111d37
Revises: c7f9e56c7a20
Create Date: 2026-08-25 11:11:52.793787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60ded111d37'
down_revision: Union[str, None] = 'c7f9e56c7a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_content_type_rating', 'contents', ['content_type', 'imdb_rating'], unique=False)
    op.create_index('idx_content_type_release', 'contents', ['content_type', 'release_date'], unique=False)
    op.create_index(op.f('ix_contents_content_type'), 'contents', ['content_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_content_type'), table_name='contents')
    op.drop_index('idx_content_type_release', table_name='contents')
    op.drop_index('idx_content_type_rating', table_name='contents')
    # ### end Alembic commands ###
