"""Initial schema setup

Revision ID: f7fe92c3508b
Revises: 
Create Date: 2026-08-15 00:37:24.959506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fe92c3508b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_index(op.f('ix_contents_imdb_id'), 'contents', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_contents_imdb_rating'), 'contents', ['imdb_rating'], unique=False)
    op.create_index(op.f('ix_contents_release_date'), 'contents', ['release_date'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_index(op.f('ix_contents_tmdb_id'), 'contents', ['tmdb_id'], unique=True)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_tmdb_id'), 'genres', ['tmdb_id'], unique=True)
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=False)
    op.create_index(op.f('ix_persons_tmdb_id'), 'persons', ['tmdb_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('cast_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cast_credits_id'), 'cast_credits', ['id'], unique=False)
    op.create_table('content_genres',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_genres')
    op.drop_index(op.f('ix_cast_credits_id'), table_name='cast_credits')
    op.drop_table('cast_credits')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_persons_tmdb_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_genres_tmdb_id'), table_name='genres')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_contents_tmdb_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_release_date'), table_name='contents')
    op.drop_index(op.f('ix_contents_imdb_rating'), table_name='contents')
    op.drop_index(op.f('ix_contents_imdb_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_table('contents')
    # ### end Alembic commands ###
